apiVersion: v1
kind: Service
metadata:
  name: managed-db-svc
  namespace: managed-db
spec:
  type: ClusterIP
  selector:
    app: managed-db
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
