#cicd workflow
name: CICD
on:
    workflow_dispatch:
permissions:
  contents: write
  id-token: write
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v5
            
            - name: Setup php
              uses: shivammathur/setup-php@v2
              with:
                php-version: '8.2'
                tools: composer

            - name: Install Dependencies
              run: composer install --no-interaction --no-progress --prefer-dist

            - name: Run tests (php unit test)
              run: vendor/bin/phpunit --color=always tests/

            - name: Lint (php code sniffer)
              run: |
                  vendor/bin/phpcs --standard=PSR12 src/ || true
    push:
      runs-on: ubuntu-latest
      needs: build
      steps:
            - name: Checkout Code
              uses: actions/checkout@v5
                  
            - name: Docker Login
              uses: docker/login-action@v3
              with: 
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Docker build and tag
              uses: docker/build-push-action@v5
              with:
                context: .
                push: false
                tags: ${{ secrets.DOCKER_USERNAME }}/frontend:${{ github.sha }}
            
            - name: Trivy Scan
              uses: aquasecurity/trivy-action@0.20.0
              with:
                image-ref: ${{ secrets.DOCKER_USERNAME }}/frontend:${{ github.sha }}
                severity: HIGH,CRITICAL
                ignore-unfixed: true
                exit-code: 1

            - name: Push Image (only if passes trivy scan)
              uses: docker/build-push-action@v5
              with:
                context: .
                push: true
                tags: ${{ secrets.DOCKER_USERNAME }}/frontend:${{ github.sha }}
    deploy:
      runs-on: ubuntu-latest
      needs: push
      outputs:
        target: ${{ steps.target.outputs.target }}
      steps:
        - name: Checkout Code
          uses: actions/checkout@v5
          with:
            ref: main
            token: ${{ secrets.GITHUB_TOKEN }}

        - name: Read current stable color environment
          id: color
          run: |
            CURRENT=$(cat aks/current-color.txt )
            echo "current=$CURRENT" >> $GITHUB_OUTPUT

        - name: Decide target color environment
          id: target
          run: |
            if [ "${{ steps.color.outputs.current }}" = "blue" ]; then
              echo "target=green" >> $GITHUB_OUTPUT
            else 
              echo "target=blue" >> $GITHUB_OUTPUT
            fi

        - name: Update Deployment.yaml manifest of the target env
          run: |
            sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/frontend:${{ github.sha }}|g" aks/deployment-${{ steps.target.outputs.target }}.yaml

        - name: Commit and push the changes
          run: |
            git config --global user.name 'sohummnm'
            git config --global user.email 'sohamkanoj55@gmail.com'
            git add aks/deployment-${{ steps.target.outputs.target }}.yaml
            git commit -m "[skip ci] Deploy image ${{ secrets.DOCKER_USERNAME}}/frontend:${{ github.sha }} to aks/deployment-${{ steps.target.outputs.target }}.yaml"
            git push origin main
    validate:
      needs: deploy
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Code
          uses: actions/checkout@v5

        - name: Azure Login (OIDC)
          uses: azure/login@v2
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID }}
            
        - name: Setup Kubectl
          uses: azure/setup-kubectl@v3
          with:
            version: latest

        - name: Get aks credentials[kube config]
          run: |
              az aks get-credentials \
              --resource-group ${{ vars.RESOURCE_GROUP }} \
              --name ${{ vars.AKS_CLUSTER_NAME }} \
              --overwrite-existing

        - name: validate
          run: |
            kubectl get pods -n project 
            kubectl run curlpod --namespace project --annotations "sidecar.istio.io/inject=false" --rm --image=curlimages/curl --restart=Never -- curl frontend-service-${{ needs.deploy.outputs.target }}.project.svc.cluster.local

    switch-traffic:
      runs-on: ubuntu-latest
      needs: [deploy, validate]
      if: success()
      steps:
        - name: Checkout Code
          uses: actions/checkout@v5

        - name: Switch Virtual Service weights
          run: |
            # Set blue = 100, green=0 or vice versa
            if [ "${{ needs.deploy.outputs.target }}" = "green" ]; then
              sed -i "s|subset: blue.*weight: [0-9]*|subset: blue\n      weight: 0|g" aks/istio-virtualservice.yaml
              sed -i "s|subset: green.*weight: [0-9]*|subset: green\n      weight: 100|g" aks/istio-virtualservice.yaml
            else
              sed -i "s|subset: blue.*weight: [0-9]*|subset: blue\n      weight: 100|g" aks/istio-virtualservice.yaml
              sed -i "s|subset: green.*weight: [0-9]*|subset: green\n      weight: 0|g" aks/istio-virtualservice.yaml
            fi
        
        - name: Update current-color.txt
          run: |
            echo "${{ needs.deploy.outputs.target }}" > aks/current-color.txt
            git config --global user.name 'sohummnm'
            git config --global user.email 'sohamkanoj55@gmail.com'
            git add aks/istio-virtualservice.yaml aks/current-color.txt
            git commit -m "[skip ci] Switched Traffic to ${{ needs.deploy.outputs.target }} Environment"
            git push
    rollback:
      runs-on: ubuntu-latest
      needs: [deploy, validate]
      if: failure()
      steps:
        - name: Checkout Code
          uses: actions/checkout@v5

        - name: Rollback Virtual Service
          run: |
            PREV=$(cat aks/current-color.txt)
            if [ "$PREV" = "blue" ]; then
              sed -i "s|subset: blue.*weight: [0-9]*|subset: blue\n      weight: 100|g" aks/istio-virtualservice.yaml
              sed -i "s|subset: green.*weight: [0-9]*|subset: green\n      weight: 0|g" aks/istio-virtualservice.yaml
            else
              sed -i "s|subset: green.*weight: [0-9]*|subset: green\n      weight: 100|g" aks/istio-virtualservice.yaml
              sed -i "s|subset: blue.*weight: [0-9]*|subset: blue\n      weight: 0|g" aks/istio-virtualservice.yaml
            fi
            git config --global user.name 'sohummnm'
            git config --global user.email 'sohamkanoj55@gmail.com'
            git add aks/istio-virtualservice.yaml
            git commit -m "[skip ci] Rolled back to $PREV"
            git push
