#cicd workflow
name: CICD
on:
    workflow_dispatch:
jobs:
    build-stage:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            
            - name: Setup php
              uses: shivammathur/setup-php@v2
              with:
                php-version: '8.2'
                tools: composer

            - name: Install Dependencies
              run: composer install --no-interaction --no-progress --prefer-dist

            - name: Run tests (php unit test)
              run: vendor/bin/phpunit --color=always tests/

            - name: Lint (php code sniffer)
              run: |
                  vendor/bin/phpcs --standard=PSR12 src/ || true
                  
            - name: Docker Login
              uses: docker/login-action@v3
              with: 
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Docker build and tag
              uses: docker/build-push-action@v5
              with:
                context: .
                push: false
                tags: ${{ secrets.DOCKER_USERNAME }}/frontend:${{ github.sha }}
            
            - name: Trivy Scan
              uses: aquasecurity/trivy-action@0.20.0
              with:
                image-ref: ${{ secrets.DOCKER_USERNAME }}/frontend:${{ github.sha }}
                severity: HIGH,CRITICAL
                ignore-unfixed: true
                exit-code: 1

            - name: Push Image (only if passes trivy scan)
              uses: docker/build-push-action@v5
              with:
                context: .
                push: true
                tags: ${{ secrets.DOCKER_USERNAME }}/frontend:${{ github.sha }}




